import type { Metadata } from "next";
import { Inter } from "next/font/google";
import "./globals.scss";
// import Header from "./components/header/Header";
// import Footer from "./components/footer/Footer";
// import SignUp from "./signup/page";
import Layout from "./components/Layout";
import { ToastContainer } from "react-toastify";
import "bootstrap/dist/css/bootstrap.min.css"; 
import "react-toastify/ReactToastify.min.css";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Eatly",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        {/* <Header /> */}
        <Layout>{children}</Layout>
        <ToastContainer />
        {/* <Footer/> */}
      </body>
    </html>
  );
}
